Pazaryeri.Web/Areas/Admin/Controllers/DashboardController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Pazaryeri.DTO.DTOs;
using Pazaryeri.Entities.Concrete;
using Pazaryeri.Web.BaseControllers;
using Pazaryeri.Web.StringInfo;

namespace Pazaryeri.Web.Areas.Admin.Controllers
{

    [Area(AreaInfo.Admin)]
    [Authorize(Roles = RoleInfo.Admin)]
 
    public class DashboardController : BaseIdentityController
    {
        private readonly SignInManager<AppUser> _signInManager;
        public DashboardController(UserManager<AppUser> userManager, SignInManager<AppUser> signInManager) : base(userManager)
        {
            _signInManager = signInManager;

        }

        public IActionResult Index()
        {
            return View();
        }

      
    }
}

Pazaryeri.Web/Areas/Magaza/Controllers/UrunController.cs
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Pazaryeri.Entities.Concrete;
using Pazaryeri.Web.BaseControllers;
using Pazaryeri.Web.StringInfo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Pazaryeri.Web.Areas.Magaza.Controllers
{
    [Area(AreaInfo.Magaza)]
    [Authorize(Roles = RoleInfo.Magaza)]
    public class UrunController : BaseIdentityController
    {
        public UrunController(UserManager<AppUser> userManager) : base(userManager)
        {
        }

        public IActionResult Index()
        {
            return View();
        }




        public IActionResult UrunEkle()
        {
            return View();
        }
    }
}

Pazaryeri.Web/Areas/Magaza/Views/Shared/_Aside.cshtml
<div class="sidenav bg-dark">
    <div id="layout-sidenav" class=" container layout-sidenav-horizontal sidenav-horizontal flex-grow-0 bg-dark">
        <ul class="sidenav-inner">

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-home"></i>
                    <div>Kontrol Panel</div>

                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Default</div>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-settings"></i>
                    <div>Genel İşlemler</div>

                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a asp-area="Magaza" asp-controller="Dashboard" asp-action="KategoriTalep" class="sidenav-link">
                            <div>Kategori Talep</div>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-shopping-cart"></i>
                    <div>Ürün Yönetimi</div>
                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a asp-controller="Urun" asp-action="UrunEkle" class="sidenav-link">
                            <div>Ürün Ekle</div>
                        </a>
                    </li>
 
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>
                                Mağazadaki Ürünler
                            </div>
                        </a>
                    </li>
 
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>
                                Çoklu Fiyat Sistemi
                            </div>
                        </a>
                    </li>
 
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>
                                Kategori Oluştur(Yoksa)
                            </div>
                        </a>
                    </li>
 
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Seçenek Oluştur(Yoksa)</div>
                        </a>
                    </li>
                </ul>


            </li>

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-download"></i>
                    <div>Siparişlerim</div>

                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Default</div>
                        </a>
                    </li>
                </ul>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Default2</div>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-trending-up"></i>
                    <div>Raporlar</div>

                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Default</div>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-layers"></i>
                    <div>Kargo Ayarları</div>

                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Default</div>
                        </a>
                    </li>
                </ul>
            </li>

            <li class="sidenav-item">
                <a href="javascript:" class="sidenav-link sidenav-toggle">
                    <i class="sidenav-icon feather icon-user-check"></i>
                    <div>Profilim</div>

                </a>
                <ul class="sidenav-menu">
                    <li class="sidenav-item">
                        <a href="index.html" class="sidenav-link">
                            <div>Default</div>
                        </a>
                    </li>
                </ul>
            </li>


        </ul>
    </div>
</div>

Pazaryeri.Web/Areas/Magaza/Views/Shared/_MagazaLayout.cshtml
<!DOCTYPE html>
<html lang="tr" class="default-style">

<head>
    <title>Mağaza Paneli | Pazayeri</title>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=no, minimum-scale=1.0, maximum-scale=1.0">

    <link rel="icon" type="image/x-icon" href="~/assets/img/favicon.ico">

    <link href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700" rel="stylesheet">

    <link rel="stylesheet" href="~/assets/fonts/fontawesome.css">
    <link rel="stylesheet" href="~/assets/fonts/ionicons.css">
    <link rel="stylesheet" href="~/assets/fonts/linearicons.css">
    <link rel="stylesheet" href="~/assets/fonts/open-iconic.css">
    <link rel="stylesheet" href="~/assets/fonts/pe-icon-7-stroke.css">
    <link rel="stylesheet" href="~/assets/fonts/feather.css">

    <link rel="stylesheet" href="~/assets/css/bootstrap-material.css">
    <link rel="stylesheet" href="~/assets/css/shreerang-material.css">
    <link rel="stylesheet" href="~/assets/css/uikit.css">

    <link rel="stylesheet" href="~/assets/libs/perfect-scrollbar/perfect-scrollbar.css">
    <link rel="stylesheet" href="~/assets/libs/flot/flot.css">
    <link href="~/devextreme/css/dx.common.css" rel="stylesheet" />
    <link href="~/devextreme/css/dx.light.css" rel="stylesheet" />

    @RenderSection("Css", false)
    <script src="https://code.jquery.com/jquery-3.5.1.min.js"></script>
    <script src="~/devextreme/js/dx.all.js"></script>
    <script src="https://unpkg.com/devextreme-aspnet-data@2.6.1/js/dx.aspnet.data.js"></script>
    <script src="~/assets/libs/morris/morris.js"></script>

</head>
<body>

    <div class="page-loader">
        <div class="bg-primary"></div>
    </div>


    <div class="layout-wrapper layout-1 layout-without-sidenav">
        <div class="layout-inner">

            @await Html.PartialAsync("_Navbar.cshtml")
            @await Html.PartialAsync("_Aside.cshtml")


            <div class="layout-container">
                @RenderBody()

            </div>

        </div>
    </div>


    <script src="~/assets/js/pace.js"></script>
    <script src="~/assets/libs/popper/popper.js"></script>
    <script src="~/assets/js/bootstrap.js"></script>
    <script src="~/assets/js/sidenav.js"></script>
    <script src="~/assets/js/layout-helpers.js"></script>
    <script src="~/assets/js/material-ripple.js"></script>

    <script src="~/assets/libs/perfect-scrollbar/perfect-scrollbar.js"></script>
    <script src="~/assets/libs/eve/eve.js"></script>
    <script src="~/assets/libs/flot/flot.js"></script>
    <script src="~/assets/libs/flot/curvedLines.js"></script>
    <script src="~/assets/libs/chart-am4/core.js"></script>
    <script src="~/assets/libs/chart-am4/charts.js"></script>
    <script src="~/assets/libs/chart-am4/animated.js"></script>

    <script src="~/assets/js/demo.js"></script>
    <script src="~/assets/libs/raphael/raphael.js"></script>


    <script src="~/assets/js/analytics.js"></script>
    <script src="~/js/pages/dashboards_ecommerce.js"></script>
    @RenderSection("Js", false)

</body>

</html>

Pazaryeri.Web/Areas/Magaza/Views/Shared/_Navbar.cshtml
<nav class="layout-navbar navbar navbar-expand-lg align-items-lg-center bg-white" id="layout-navbar">
    <div class="container">
        <a href="index.html" class="navbar-brand app-brand demo d-lg-none py-0 mr-4">
            <span class="app-brand-logo demo">
                <img src="~/assets/img/logo-dark.png" alt="Brand Logo" class="img-fluid">
            </span>
            <span class="app-brand-text demo font-weight-normal ml-2">Empire</span>
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#layout-navbar-collapse">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse" id="layout-navbar-collapse">

            <hr class="d-lg-none w-100 my-2">
            <div class="navbar-nav align-items-lg-center">

                <label class="nav-item navbar-text navbar-search-box p-0 active">
                    <i class="feather icon-search navbar-icon align-middle"></i>
                    <span class="navbar-search-input pl-2">
                        <input type="text" class="form-control navbar-text mx-2" placeholder="Search...">
                    </span>
                </label>
            </div>
            <div class="navbar-nav align-items-lg-center ml-auto">
                <div class="demo-navbar-notifications nav-item dropdown mr-lg-3">
                    <a class="nav-link dropdown-toggle hide-arrow" href="#" data-toggle="dropdown">
                        <i class="feather icon-bell navbar-icon align-middle"></i>
                        <span class="badge badge-danger badge-dot indicator"></span>
                        <span class="d-lg-none align-middle">&nbsp; Notifications</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="bg-primary text-center text-white font-weight-bold p-3">
                            4 New Notifications
                        </div>
                        <div class="list-group list-group-flush">
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <div class="ui-icon ui-icon-sm feather icon-home bg-secondary border-0 text-white"></div>
                                <div class="media-body line-height-condenced ml-3">
                                    <div class="text-dark">Login from 192.168.1.1</div>
                                    <div class="text-light small mt-1">
                                        Aliquam ex eros, imperdiet vulputate hendrerit et.
                                    </div>
                                    <div class="text-light small mt-1">12h ago</div>
                                </div>
                            </a>
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <div class="ui-icon ui-icon-sm feather icon-user-plus bg-info border-0 text-white"></div>
                                <div class="media-body line-height-condenced ml-3">
                                    <div class="text-dark">
                                        You have
                                        <strong>4</strong> new followers
                                    </div>
                                    <div class="text-light small mt-1">
                                        Phasellus nunc nisl, posuere cursus pretium nec, dictum vehicula tellus.
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <div class="ui-icon ui-icon-sm feather icon-power bg-danger border-0 text-white"></div>
                                <div class="media-body line-height-condenced ml-3">
                                    <div class="text-dark">Server restarted</div>
                                    <div class="text-light small mt-1">
                                        19h ago
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <div class="ui-icon ui-icon-sm feather icon-alert-triangle bg-warning border-0 text-dark"></div>
                                <div class="media-body line-height-condenced ml-3">
                                    <div class="text-dark">99% server load</div>
                                    <div class="text-light small mt-1">
                                        Etiam nec fringilla magna. Donec mi metus.
                                    </div>
                                    <div class="text-light small mt-1">
                                        20h ago
                                    </div>
                                </div>
                            </a>
                        </div>
                        <a href="javascript:" class="d-block text-center text-light small p-2 my-1">Show all notifications</a>
                    </div>
                </div>
                <div class="demo-navbar-messages nav-item dropdown mr-lg-3">
                    <a class="nav-link dropdown-toggle hide-arrow" href="#" data-toggle="dropdown">
                        <i class="feather icon-mail navbar-icon align-middle"></i>
                        <span class="badge badge-success badge-dot indicator"></span>
                        <span class="d-lg-none align-middle">&nbsp; Messages</span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <div class="bg-primary text-center text-white font-weight-bold p-3">
                            4 New Messages
                        </div>
                        <div class="list-group list-group-flush">
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <img src="~/assets/img/avatars/6-small.png" class="d-block ui-w-40 rounded-circle" alt>
                                <div class="media-body ml-3">
                                    <div class="text-dark line-height-condenced">Lorem ipsum dolor consectetuer elit.</div>
                                    <div class="text-light small mt-1">
                                        Josephin Doe &nbsp;·&nbsp; 58m ago
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <img src="~/assets/img/avatars/4-small.png" class="d-block ui-w-40 rounded-circle" alt>
                                <div class="media-body ml-3">
                                    <div class="text-dark line-height-condenced">Lorem ipsum dolor sit amet, consectetuer.</div>
                                    <div class="text-light small mt-1">
                                        Lary Doe &nbsp;·&nbsp; 1h ago
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <img src="~/assets/img/avatars/5-small.png" class="d-block ui-w-40 rounded-circle" alt>
                                <div class="media-body ml-3">
                                    <div class="text-dark line-height-condenced">Lorem ipsum dolor sit amet elit.</div>
                                    <div class="text-light small mt-1">
                                        Alice &nbsp;·&nbsp; 2h ago
                                    </div>
                                </div>
                            </a>
                            <a href="javascript:" class="list-group-item list-group-item-action media d-flex align-items-center">
                                <img src="~/assets/img/avatars/11-small.png" class="d-block ui-w-40 rounded-circle" alt>
                                <div class="media-body ml-3">
                                    <div class="text-dark line-height-condenced">Lorem ipsum dolor sit amet consectetuer amet elit dolor sit.</div>
                                    <div class="text-light small mt-1">
                                        Suzen &nbsp;·&nbsp; 5h ago
                                    </div>
                                </div>
                            </a>
                        </div>
                        <a href="javascript:" class="d-block text-center text-light small p-2 my-1">Show all messages</a>
                    </div>
                </div>

                <div class="nav-item d-none d-lg-block text-big font-weight-light line-height-1 opacity-25 mr-3 ml-1">|</div>
                <div class="demo-navbar-user nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" data-toggle="dropdown">
                        <span class="d-inline-flex flex-lg-row-reverse align-items-center align-middle">
                            <img src="~/assets/img/avatars/1.png" alt class="d-block ui-w-30 rounded-circle">
                            <span class="px-1 mr-lg-2 ml-2 ml-lg-0">Cindy Deitch</span>
                        </span>
                    </a>
                    <div class="dropdown-menu dropdown-menu-right">
                        <a href="javascript:" class="dropdown-item">
                            <i class="feather icon-user text-muted"></i> &nbsp; My profile
                        </a>
                        <a href="javascript:" class="dropdown-item">
                            <i class="feather icon-mail text-muted"></i> &nbsp; Messages
                        </a>
                        <a href="javascript:" class="dropdown-item">
                            <i class="feather icon-settings text-muted"></i> &nbsp; Account settings
                        </a>
                        <div class="dropdown-divider"></div>
                        <a href="javascript:" class="dropdown-item">
                            <i class="feather icon-power text-danger"></i> &nbsp; Log Out
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
</nav>